version: 2.1
jobs:
  build:  
    working_directory: ~/circleci-python
  docker:
    image: "circle/python:3.6.4"
  steps:
      - checkout
      - run: /bin/python3 /home/abdullah/Python/main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circle/python:3.6.4"
    steps:
      - checkout:
      - run: /bin/python3 /home/abdullah/Python/main-test.py

workflows:
  build_and_test:
    jobs:
      - build:
      - test:
          requires:
            - build