version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.13.0
    working_directory: ~/circleci-python
    steps:
      - checkout
      - run: /bin/python3 /home/abdullah/Python/main.py
  test:
    docker:
      - image: cimg/python:3.13.0
    working_directory: ~/circleci-python
    steps:
      - checkout
      - run: /bin/python3 /home/abdullah/Python/main-test.py
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build